name: Terraform Deploy
on:
  workflow_dispatch:
  
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # The ARN from Step 3
          aws-region: ap-southeast-1 # Philippines/Singapore region
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform 
        run: terraform init -backend-config="bucket=hebrewsapp-497162053259-ap-southeast-1-an"

      - name: Terraform Plan & Apply
        working-directory: ./terraform 
        run: terraform apply -auto-approve -var="db_password=${{ secrets.TF_VAR_db_password }}"

         # --- NEW DOCKER & ECS STEPS START HERE ---

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hebrews-api # Must match your main.tf ECR name
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS Express Mode
        uses: aws-actions/amazon-ecs-deploy-express-service@v1
        with:
          service-name: hebrews-api # Must match your main.tf service name
          image: ${{ steps.login-ecr.outputs.registry }}/hebrews-api:latest  

